[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.4"
edition = "2021"

[workspace.dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"]}
owo-colors = "4.2.0"
chrono = "0.4.40"
tracing-core = "0.1.33"
