[package]
name = "clerk"
version.workspace = true
edition.workspace = true

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
owo-colors = { workspace = true }
chrono = { workspace = true }
tracing-core = { workspace = true }
