package:
  version: 0.0.18
  name: toolbox-py
build:
  noarch: python
  script:
    - if: linux
      then:
        - pwsh -f $RECIPE_DIR/build-toolbox-py.ps1

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python >= 3.11
    - lazy-loader
    - rich

tests:
  - python:
      imports:
        - toolbox
