[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.0.15"

[workspace.dependencies]
chrono = { version = "0.4.40" }
owo-colors = { version = "4.2.0" }
tracing = { version = "0.1.41" }
tracing-core = { version = "0.1.33" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
