[project]
authors = [{ name = "Glatzel", email = "893016099@qq.com" }]
dependencies = ["lazy-loader", "rich"]
dynamic = ["version"]
name = "clerk"
requires-python = ">=3.11"

[tool.pyright]
reportShadowedImports = false

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tool.pixi.dependencies]
python = "3.11.*"
rattler-build = "==0.41.0"
# test
pytest = "==8.3.5"
pytest-cov = "==6.1.1"
