[project]
authors = [{ name = "Glatzel", email = "893016099@qq.com" }]
dependencies = ["lazy-loader", "rich"]
dynamic = ["version"]
name = "toolbox"
requires-python = ">=3.11"

[tool.pyright]
reportShadowedImports = false

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[tool.pixi.dependencies]
python = "3.11.*"
rattler-build = "==0.43.1"
# test
pyfakefs = "==5.7.4"
pytest = "==8.4.0"
pytest-cov = "==6.2.1"
