[project]
authors = [{ name = "Glatzel", email = "893016099@qq.com" }]
dependencies = ["lazy-loader", "rich"]
dynamic = ["version"]
name = "clerk"
requires-python = ">=3.11"

[tool.pyright]
reportShadowedImports = false

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[tool.pixi.dependencies]
python = "3.11.*"
rattler-build = "==0.42.1"
# test
pytest = "==8.3.5"
pytest-cov = "==6.1.1"
pyfakefs = "==5.7.4"