name: rust-CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false

permissions: read-all

env:
  RUST_ROOT: ./rust

jobs:
  cargo-test:
    if: ${{!inputs.release}}
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - run: choco install pkgconfiglite
        if: ${{runner.os == 'Windows'}}
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          run-install: false

      - name: restore vcpkg
        if: ${{ runner.os == 'Windows'}}
        uses: actions/cache/restore@v4
        with:
          path: ./rust/vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('./rust/vcpkg/vcpkg.json') }}

      - uses: dtolnay/rust-toolchain@nightly

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: cargo-test
        run: ${{env.RUST_ROOT}}/scripts/cargo-test.ps1
        shell: pwsh

      - name: Upload results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  check:
    if: ${{!inputs.release}}
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: cargo-fmt
        if: ${{!cancelled()}}
        run: ${{env.RUST_ROOT}}/scripts/cargo-fmt.ps1
        shell: pwsh

      - name: cargo-clippy
        if: ${{!cancelled()}}
        run: ${{env.RUST_ROOT}}/scripts/cargo-clippy.ps1
        shell: pwsh

      - name: cargo-machete
        if: ${{!cancelled()}}
        uses: bnjbvr/cargo-machete@main
